### ISSUE TITLE
Cannot follow another user

### ISSUE THREAD

**Issue by TikoyX** [DevOps-CI-CDont/DevOps-CI-CDont#37]
I see no option to find other users, and i dont know if there is a user-page at all.
i therefore assume i cant follow other users

**Comment by kjaerb** [comment]
Hi, there should be a lot of tweets on the ![public timeline](http://138.68.93.147:3000/public). When you see a tweet, then you can click on their profile picture or on their username to go to their page and follow/unfollow them.
