### ISSUE TITLE
Bug: Memory issue in API container

### ISSUE THREAD

**Issue by EraxterCodes** [DevOps-CI-CDont/DevOps-CI-CDont#58]

**Comment by Jacelius** [comment]
![Image](https://user-images.githubusercontent.com/13639759/230724717-d6692c81-6e8d-45ca-b3c7-780008851a4c.png)

^Docker stats view

Kibana seems to use a significant chunk of memory. 
API container grows steadily in memory until it crashes

**Comment by Jacelius** [comment]
Same behavior without all the other containers 

![Image](https://user-images.githubusercontent.com/13639759/230730250-207034d5-f120-4f00-8f9f-5e59b8c530d5.png)

I think the metrics data structures (consuming RAM) are steadily growing in size..

**Comment by Jacelius** [comment]
We could say that this is ok, if we don't need any "total metrics over a long time" and we are fine with "resetting" our metrics every now and then ...

**Comment by Jacelius** [comment]
If we could get the metrics in the API that Prometheus fetches to be stored in a volume instead of RAM it would be fixed ..

**Comment by Jacelius** [comment]
It seems to NOT be metric related actually. maybe read this https://hackernoon.com/avoiding-memory-leak-in-golang-api-1843ef45fca8

**Comment by Jacelius** [comment]
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body

I believe this has been the issue. It's not 100% solved, but I think most of the cases are..
