### ISSUE TITLE
Why are there no followers

### ISSUE THREAD

**Issue by EraxterCodes** [DevOps-CI-CDont/DevOps-CI-CDont#67]
Also no new registered users (except some from test suite) since March 18

**Comment by Jacelius** [comment]
Conclusion: simulator can run from local machine towards API on both live and local port 8081. 
Live logs seem to always include at least 1 of usernames (who or whom in a follow request) which don't exist in our users.

The "flllws" and "register" endpoints seem to work on 8081 live and local.

**Comment by Jacelius** [comment]
We have followers!
